### ISSUE TITLE
ReferenceError: reentry is not defined

### ISSUE THREAD

**Issue by aliabbas90** [realtymaps/promise-ftp#29]
I am actually encountering a problem while I am trying to upload a file from storage to an FTP server, passing by a triggered node js function.

So, every time a file, with a specific name, is uploaded to Firebase storage, this file should automatically be uploaded to the FTP server. To do that, I am using **promise-ftp**. I am able to connect to the server but when it comes to upload files, I am faced with a connection timeout.

But, when I execute the js script locally without passing by a trigger, the file is successfully uploaded.

My promise-ftp script that I tried locally looks like :

```
function test() {
  var ftp = new PromiseFtp();
  const tempFilePath = path.join(os.tmpdir(), '123.pdf');
  ftp.connect({host: 'ftp.aaa-bbbb.ccc', user: 'aaabbb', password: 'pswd123'})
  .then(function (serverMessage) {
    console.log(serverMessage);
    return ftp.put(tempFilePath, 'local.pdf');
  })
  .then(function () {
    return ftp.end();
  })
  .then(() => {
    console.log("Ready to delete");
     // Once the pdf has been uploaded delete the local file to free up disk space.
    fs.unlinkSync(tempFilePath);
  });
}
```

```
exports.updateToFTP = functions.storage.object().onFinalize((object) => {
    // [START eventAttributes]
    const fileBucket = object.bucket; // The Storage bucket that contains the file.
    const filePath = object.name; // File path in the bucket.
    const contentType = object.contentType; // File content type.
    const resourceState = object.resourceState; // The resourceState is 'exists' or 'not_exists' (for file/folder deletions).
    const metageneration = object.metageneration; // Number of times metadata has been generated. New objects have a value of 1.
    // [END eventAttributes]

  // [START stopConditions]
  // Exit if this is triggered on a file that is not an image.
  if (resourceState === 'exists') {
    // ignore for deletions
    return
  }
  if (!contentType.startsWith('application/pdf')) {
    return null;
  }
  // [END stopConditions]
  // Get the file name.
  const fileName = path.basename(filePath);
  // get file from bucket.
  const bucket = gcs.bucket(fileBucket);
  const tempFilePath = path.join(os.tmpdir(), fileName);
  var ftp = new PromiseFtp();
  return bucket.file(filePath).download({
    destination: tempFilePath,
  }).then(() => {
    return ftp.connect({host: 'host', user: 'usr', password: 'pwd'})
  }).then(function (serverMessage) {
    console.log(serverMessage);
    return ftp.put(tempFilePath, fileName);
  }).then(function () {
    return ftp.end();
  })
  .then(() => {
    console.log("Ready to delete");
     // Once the pdf has been uploaded delete the local file to free up disk space.
    fs.unlinkSync(tempFilePath);
  }).catch((err) => {
      console.log("Catching error");
      console.log(err)
  });
})
```
The error is : 
```
ReferenceError: reentry is not defined
    at /user_code/node_modules/promise-ftp/node_modules/@icetee/ftp/lib/connection.js:937:18
    at Timeout._onTimeout (/user_code/node_modules/promise-ftp/node_modules/@icetee/ftp/lib/connection.js:962:9)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

Any idea?

**Comment by zacronos** [comment]
I have not seen this error before.  As you can see in the stack trace you've provided, the error actually originates within the `@icetee/ftp` dependency, not `promise-ftp` itself.  I would try posting that error trace as an issue with `@icetee/ftp` and see if anyone there can help.

**Comment by JLRishe** [comment]
@zacronos It looks like this bug was [fixed](https://github.com/icetee/node-ftp/commit/a3c0efd2a071c3d822afe5f22711285162391cf8) in @icetee/ftp around version 1.0.6, but this library is still using version 0.3 of that package.

I observed this error yesterday in a downstream package that depends on yours ([ftp-deploy](https://github.com/simonh1000/ftp-deploy)).

**Comment by jamaica474** [comment]
Having same issue.

**Comment by taylorgibb** [comment]
I am also observing this issue. Seems to be what @JLRishe points out. I have patched promise-ftp to use an updated version of @icetee/ftp (1.0.8) here (https://github.com/taylorgibb/promise-ftp)
