### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Nullpo** [realtymaps/promise-ftp#4]
When I install promise-ftp, npm shows this:

    npm WARN promise-ftp@1.2.13 requires a peer of promise-ftp-common@^1.1.5 but none was installed.
    npm WARN loadftp@1.0.0 No repository field.

And when I try to execute my code, shows this:

    module.js:341
        throw err;
        ^
    
    Error: Cannot find module 'promise-ftp-common'
        at Function.Module._resolveFilename (module.js:339:15)
        at Function.Module._load (module.js:290:25)
        at Module.require (module.js:367:17)
        at require (internal/module.js:16:19)
        at Object.<anonymous> (/home/nullpo/work/programs/ftp-service/node_modules/promise-ftp/dist/promiseFtp.js:17:24)
        at Object.<anonymous> (/home/nullpo/work/programs/ftp-service/node_modules/promise-ftp/dist/promiseFtp.js:256:4)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
    
I'm using Node v5.8.0. 

Apparently the module promise-ftp-common@^1.1.5  doesn't exists for node v5

**Comment by Nullpo** [comment]
In node v5.x I have this problem.
In node v4.1, all works fine :)

**Comment by zacronos** [comment]
Please check the install instructions in the README.  You need to install `promise-ftp-common` separately if you are using npm 3+, since it no longer handles peer dependencies automatically.  (The install instructions did incorrectly reference `promise-ftp-errors`, and I've now corrected that.)
